#!/bin/bash
cd `dirname $0`

export VARIANTS=$*

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=''
    export LD_LIBRARY_PATH=../dist/lib
} else {
    export CPUCOUNT=`sysctl -n hw.ncpu`
    export TOOLSET=toolset=clang
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT $TOOLSET $VARIANTS
then {
    echo fost-base $VARIANTS OK
    exit 0
} else {
    exit 1
}
fi
