#!/bin/bash

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$*
}
fi

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=gcc
    export LD_LIBRARY_PATH=../dist/lib
    EXTENSION="so"
}
else {
    export CPUCOUNT=1
    export TOOLSET=darwin
    export DYLD_LIBRARY_PATH=../dist/lib
    EXTENSION="dylib"
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT toolset=$TOOLSET $VARIANTS
then {
    if ../dist/bin/ftest -b false \
        libfost-core-test-smoke.$EXTENSION \
        libfost-crypto-test-smoke.$EXTENSION \
        libfost-inet-test-smoke.$EXTENSION \
        libfost-jsondb-test-smoke.$EXTENSION \
        libfost-schema-test-smoke.$EXTENSION
    then {
        echo fost-base smoke tests passed
    } else {
        exit 1
    }
    fi
} else {
    exit 1
}
fi
