#!/bin/bash
cd `dirname $0`

if test -z $1
then {
    export VARIANTS=debug
} else {
    export VARIANTS=$*
}
fi

if test -e /proc/
then {
    export CPUCOUNT=`grep -c ^processor /proc/cpuinfo`
    export TOOLSET=gcc
    export LD_LIBRARY_PATH=../dist/lib
} else {
    export CPUCOUNT=1
    export TOOLSET=darwin
    export DYLD_LIBRARY_PATH=../dist/lib
    export LANG=C
}
fi

if ../bjam -j$CPUCOUNT toolset=$TOOLSET $VARIANTS
then {
    echo fost-base smoke tests passed
    exit 0
} else {
    exit 1
}
fi
